src/main/java/br/com/doutorti/salaomaisbonita/model/HolidayEntity.java
package br.com.doutorti.salaomaisbonita.model;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.doutorti.salaomaisbonita.model.utils.BaseEntities;
import br.com.doutorti.salaomaisbonita.model.utils.DateHourUtils;

@Entity
@Table(name = "holiday")
@AttributeOverride(name = "id", column = @Column(name = "pk_id_holiday"))
public class HolidayEntity extends BaseEntities<Long> {

	private static final long serialVersionUID = 11644467341461842L;

	@Column(nullable = false)
	private String name;

	@Column(nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date initialDate;

	@Column(nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date finalDate;

	public HolidayEntity() {
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getInitialDate() {
		return initialDate;
	}

	public void setInitialDate(Date initialDate) {
		this.initialDate = initialDate;
	}

	public Date getFinalDate() {
		return finalDate;
	}

	public void setFinalDate(Date finalDate) {
		this.finalDate = finalDate;
	}

	public String getDateFormat() {
		if (initialDate != null)
			return DateHourUtils.ddMMyyyy.format(initialDate);
		return null;
	}

	@Override
	public String toString() {
		return name + " - " + (initialDate != null ? DateHourUtils.ddMMyyyy.format(initialDate) : " ");
	}

}

src/main/java/br/com/doutorti/salaomaisbonita/support/holiday/HolidayAddEditMB.java
package br.com.doutorti.salaomaisbonita.support.holiday;

import java.io.IOException;
import java.util.ResourceBundle;

import javax.faces.application.Application;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.log4j.Logger;
import org.springframework.context.annotation.Scope;
import org.springframework.web.context.WebApplicationContext;

import br.com.doutorti.salaomaisbonita.model.HolidayEntity;
import br.com.doutorti.salaomaisbonita.model.repositories.IHolidayRepository;
import br.com.doutorti.salaomaisbonita.model.utils.BaseBeans;
import br.com.doutorti.salaomaisbonita.model.utils.DateHourUtils;

//ConfigurableBeanFactory.SCOPE_SINGLETON, ConfigurableBeanFactory.SCOPE_PROTOTYPE,
//WebApplicationContext.SCOPE_REQUEST, WebApplicationContext.SCOPE_SESSION
@Scope(value = WebApplicationContext.SCOPE_REQUEST)
@Named(value = "holidayAddEditMB")
public class HolidayAddEditMB extends BaseBeans {

	private static final long serialVersionUID = -7885745816896496959L;

	Logger logger = Logger.getLogger(HolidayAddEditMB.class);

	@Inject
	private IHolidayRepository holidayRepository;

	@Inject
	private FacesContext context;

	private HolidayEntity holiday;

	private String title;

	public HolidayAddEditMB() {
		this.holiday = new HolidayEntity();
	}

	public void add() {
		this.title = this.getResourceProperty("labels", "button_add");
	}

	public void update(Long id) {
		this.holiday = holidayRepository.findOne(id);
		this.title = this.getResourceProperty("labels", "button_update");
	}
	
	public void renewHoliday() {
		this.title = this.getResourceProperty("labels", "button_renewHoliday");
	}

	public void save() {
		if (this.holiday != null) {
			holiday.setInitialDate(DateHourUtils.getStartOfDay(holiday.getInitialDate()));
			holiday.setFinalDate(DateHourUtils.getEndOfDay(holiday.getInitialDate()));
			
			if (this.holiday.getId() == null) {
				this.holidayRepository.save(this.holiday);
				try {
					FacesContext.getCurrentInstance().getExternalContext().redirect("list.faces");
				} catch (IOException e) {
					e.printStackTrace();
				}
			} else {
				// Update
				this.holidayRepository.save(this.holiday);
			}
		}
	}

	public String getTitle() {
		if (holiday.getId() == null) {
			this.title = this.getResourceProperty("labels", "button_add");
		}
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	private String getResourceProperty(String resource, String label) {
		Application application = this.context.getApplication();
		ResourceBundle bundle = application.getResourceBundle(this.context, resource);

		return bundle.getString(label);
	}

	public HolidayEntity getHoliday() {
		return holiday;
	}

	public void setHoliday(HolidayEntity holiday) {
		this.holiday = holiday;
	}

}

src/main/java/br/com/doutorti/salaomaisbonita/support/holiday/HolidayMB.java
package br.com.doutorti.salaomaisbonita.support.holiday;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.inject.Inject;
import javax.inject.Named;

import org.apache.log4j.Logger;
import org.springframework.context.annotation.Scope;

import br.com.doutorti.salaomaisbonita.model.HolidayEntity;
import br.com.doutorti.salaomaisbonita.model.repositories.IHolidayRepository;
import br.com.doutorti.salaomaisbonita.model.utils.BaseBeans;

@Scope("view")
@Named(value = "holidayMB")
public class HolidayMB extends BaseBeans {

	private static final long serialVersionUID = 538532308955296799L;

	Logger logger = Logger.getLogger(HolidayMB.class);

	@Inject
	private IHolidayRepository holidayRepository;

	private List<HolidayEntity> holidays;

	private Long id;

	private Long idToDelete;

	private Integer filterYear;

	public HolidayMB() {
		filterYear = Calendar.getInstance().get(Calendar.YEAR);
	}

	public void filterHoliday() {
		if (filterYear == null) {
			filterYear = Calendar.getInstance().get(Calendar.YEAR);
		}
		this.holidays = this.holidayRepository.findByYear(filterYear);
	}

	public List<Integer> getYearsToFind() {
		List<Integer> result = new ArrayList<Integer>();
		int currentYear = Calendar.getInstance().get(Calendar.YEAR);
		for (int i = -2; i < 4; i++) {
			result.add(currentYear + i);
		}
		return result;
	}

	public void onLoad() {
		filterHoliday();
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void delete() {
		if (getIdToDelete() != null) {
			this.holidayRepository.delete(getIdToDelete());
		}
		filterHoliday();
	}

	public Long getIdToDelete() {
		return idToDelete;
	}

	public void setIdToDelete(Long idToDelete) {
		this.idToDelete = idToDelete;
	}

	public List<HolidayEntity> getHolidays() {
		return holidays;
	}

	public void setHolidays(List<HolidayEntity> holidays) {
		this.holidays = holidays;
	}

	public Integer getFilterYear() {
		return filterYear;
	}

	public void setFilterYear(Integer filterYear) {
		this.filterYear = filterYear;
	}

}

src/main/webapp/admin/pages/holiday/addEdit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui" template="../main.xhtml">

	<ui:define name="content">
		<p:button value="Buscar feriado" href="/admin/pages/holiday/list.faces" icon="ui-icon-search" />
		
		<h:form>
												
			<h:messages errorClass="error"/>
			<h:inputHidden value="#{holidayAddEditMB.holiday.id}" />

			<div class="ui-grid ui-grid-responsive">
				<p:panel header="#{holidayAddEditMB.title} #{labels.client}">
					<div class="ui-grid-row">
						<p:outputLabel styleClass="ui-grid-col-2" for="holiday_name" value="#{labels.holiday_name}: " />
						<p:inputText styleClass="ui-grid-col-10" id="holiday_name" value="#{holidayAddEditMB.holiday.name}" required="true" />
					</div>
	
					<div class="ui-grid-row">
						<p:outputLabel styleClass="ui-grid-col-2" for="holiday_date" value="#{labels.holiday_date}: " />
						<p:calendar styleClass="ui-grid-col-3" id="holiday_date" value="#{holidayAddEditMB.holiday.initialDate}" required="true" pattern="dd/MM/yyyy" navigator="true" mode="popup" mask="99/99/9999" locale="pt_BR" yearRange="c-1:c+1"/>
					</div>
	
					<p:commandButton value="#{labels.button_save}"
						action="list.faces" actionListener="#{holidayAddEditMB.save}"
						style="margin: 130 auto;" ajax="false" />
				</p:panel>
			</div>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/admin/pages/holiday/list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui" template="../main.xhtml">

	<ui:define name="content">
		<f:view>
			<f:event listener="#{holidayMB.onLoad}" type="preRenderView" />
		</f:view>

		<h:form id="holidayForm">
		<p:commandButton widgetVar="addButton" value="#{labels.button_add}"
					action="/admin/pages/holiday/addEdit.faces" ajax="false"
					actionListener="#{holidayAddEditMB.add}" />
		
		<p:panel id="holidayPanel" header="#{labels.holiday}">
				<p:outputLabel styleClass="ui-grid-col-2" for="filterYear" value="#{labels.holiday_year}"/>
				<p:selectOneMenu id="filterYear" value="#{holidayMB.filterYear}" >
					<f:selectItems value="${holidayMB.yearsToFind}" />
				</p:selectOneMenu>
				<p:commandButton id="buttonFind" value="Consultar" actionListener="#{holidayMB.filterHoliday}" process="@form" update="holidayPanel"/>
				<p:dataTable id="holidayDataTable" widgetVar="dataTable" var="holiday" 
					value="#{holidayMB.holidays}" rowKey="#{holiday.id}" tableStyleClass="ui-table-columntoggle">
					<p:column width="55">
							<f:facet name="header">
								<h:outputText value="Ação" />
							</f:facet>
							<div style="text-align: center;">
								<p:commandButton icon="ui-icon-edit"
									update="holidayDataTable" 
									action="/admin/pages/holiday/addEdit.faces"
									actionListener="#{holidayAddEditMB.update(holiday.id)}" />
								<p:commandButton icon="ui-icon-delete" 
								actionListener="#{holidayMB.setIdToDelete(holiday.id)}" onclick="PF('dialog_delete').show()"/>
							</div>
					</p:column>

					<p:column>
						<f:facet name="header">
							<h:outputText value="#{labels.holiday_name}" />
						</f:facet>
						<h:outputText value="#{holiday.name}" />
					</p:column>
					
					<p:column>
						<f:facet name="header">
							<h:outputText value="#{labels.holiday_date}" />
						</f:facet>
						<h:outputText value="#{holiday.dateFormat}" />
					</p:column>
					
				</p:dataTable>
		</p:panel>
		</h:form>
				<p:dialog id="dialog_delete" widgetVar="dialog_delete" closable="false" resizable="false" appendTo="@(body)" 
					position="center" modal="true" width="200" height="70" header="Confirmar?">
						<p><h:outputText value="Deseja Excluir?" /></p>
						<div style="text-align: center;">
							<p:commandButton value="Sim" onclick="PF('dialog_delete').hide()" 
							actionListener="#{holidayMB.delete}" process="@this" update="holidayForm"/>
							<p:commandButton value="Não" type="button" onclick="PF('dialog_delete').hide()" />
						</div>
				</p:dialog>
	</ui:define>
</ui:composition>

src/main/webapp/admin/pages/holiday/renewHoliday.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui" template="../main.xhtml">

	<ui:define name="content">
		<p:button value="Buscar feriado" href="/admin/pages/holiday/list.faces" icon="ui-icon-search" />
		
		<h:form>
												
			<h:messages errorClass="error"/>

			<div class="ui-grid ui-grid-responsive">
				<p:panel header="#{holidayAddEditMB.title} #{labels.client}">
					<div class="ui-grid-row">
						<p:outputLabel styleClass="ui-grid-col-2" for="holiday_name" value="#{labels.holiday_name}: " />
						<p:inputText styleClass="ui-grid-col-10" id="holiday_name" value="#{holidayAddEditMB.holiday.name}" required="true" />
					</div>
	
					<div class="ui-grid-row">
						<p:outputLabel styleClass="ui-grid-col-2" for="holiday_date" value="#{labels.holiday_date}: " />
						<p:calendar styleClass="ui-grid-col-3" id="holiday_date" value="#{holidayAddEditMB.holiday.initialDate}" required="true" pattern="dd/MM/yyyy" navigator="true" mode="popup" mask="99/99/9999" locale="pt_BR" yearRange="c-1:c+1"/>
					</div>
	
					<p:commandButton value="#{labels.button_save}"
						action="list.faces" actionListener="#{holidayAddEditMB.save}"
						style="margin: 130 auto;" ajax="false" />
				</p:panel>
			</div>
		</h:form>
	</ui:define>
</ui:composition>